function [ pitGeomS ] = nullPitGeomS(pitGS)

pitGeomS = struct(...
    'label', '',...
    'file', '',...
    'outlier', '', ...
    'pitVol', '', ...
    'pitVolSD', '', ...
    'pitDepth', '', ...
    'pitDepthSD', '', ...
    'ellipseArea', '', ...
    'ellipseAreaSD', '', ...
    'polishedElev', '', ...
    'polishedElevSD', '', ...
    'polishedElevSDPlus', '', ...
    'polishedElevSDMinus', '', ...
    'pitFloorElev', '', ... 
    'pitFloorElevSD', '', ... 
    'ellipseA', '', ...
    'ellipseB', '', ...
    'ellipsePhi', '', ...
    'ellipseXc', '', ...
    'ellipseYc', '', ...
    'independentEllipse', '');

pitGeomS.label = '';
pitGeomS.file = '';
pitGeomS.pitVol = nan;
pitGeomS.pitVolSD = nan;
pitGeomS.pitDepth = nan;
pitGeomS.pitDepthSD = nan;
pitGeomS.ellipseArea = nan;
pitGeomS.polishedElev = nan;
pitGeomS.polishedElevSD = nan;
pitGeomS.polishedElevSDPlus = nan;
pitGeomS.polishedElevSDMinus = nan;
pitGeomS.pitFloorElev = nan;
pitGeomS.pitFloorElevSD = nan;
pitGeomS.ellipseA = nan;
pitGeomS.ellipseB = nan;
pitGeomS.ellipsePhi = nan;
pitGeomS.ellipseXc = nan;
pitGeomS.ellipseYc = nan;
pitGeomS.independentEllipse = [];

if nargin == 1 && ~isempty(pitGS)
    pitGeomS.label = pitGS.label;
    pitGeomS.file = pitGS.file;
    pitGeomS.independentEllipse = pitGS.independentEllipse;
end

end